### ISSUE TITLE
Erreur export Xia 2.2

### ISSUE THREAD

**Issue by sarahlachise** [pfautrero/xia#15]
Une image png (2000px de large, 4.9Mo), un détail (ellipse) qui pointe vers une autre ressource Xia, export Material. 

message d'erreur :

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Inkscape\python\lib\lib-tk\Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "C:\Program Files\Inkscape\share\extensions\xiaconverter\mainwindow.py", line 134, in <lambda>
    button["command"] = lambda t=theme:self.createIA(t)
  File "C:\Program Files\Inkscape\share\extensions\xiaconverter\mainwindow.py", line 295, in createIA
    self.imageActive.analyzeSVG(self.filename, maxNumPixels)
  File "C:\Program Files\Inkscape\share\extensions\xiaconverter\iaobject.py", line 214, in analyzeSVG
    self.xml = minidom.parse(filePath)
  File "C:\Program Files\Inkscape\python\Lib\xml\dom\minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "C:\Program Files\Inkscape\python\Lib\xml\dom\expatbuilder.py", line 924, in parse
    result = builder.parseFile(fp)
  File "C:\Program Files\Inkscape\python\Lib\xml\dom\expatbuilder.py", line 211, in parseFile
    parser.Parse("", True)
ExpatError: unclosed token: line 12, column 2

[etape1.zip](https://github.com/pfautrero/xia/files/872461/etape1.zip)

**Comment by pfautrero** [comment]
bug confirmé sur Windows7 avec XIA comme extension Inkscape. Nous allons repackager l'extension avec une version de Python plus récente. Ce sera disponible pour XIA version 2.3
